#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "$PROJECT_ROOT"

MAX_CHANGED_FILES="${STEER_RELEASE_MAX_CHANGED_FILES:-40}"
ALLOWLIST_FILE="${STEER_RELEASE_ALLOWLIST_FILE:-.release-allowlist}"
REQUIRE_ALLOWLIST="${STEER_RELEASE_REQUIRE_ALLOWLIST:-1}"
REPORT_DIR="${STEER_RELEASE_REPORT_DIR:-scenario_results}"
DIFF_MODE="${STEER_RELEASE_DIFF_MODE:-worktree}"
mkdir -p "$REPORT_DIR"
REPORT_PATH="${STEER_RELEASE_WORKTREE_REPORT:-${REPORT_DIR}/release_worktree_report_$(date +%Y%m%d_%H%M%S).txt}"
BOOTSTRAP_ALLOWLIST=0
USE_STAGED=0

while [ "$#" -gt 0 ]; do
    case "${1:-}" in
        --bootstrap-allowlist)
            BOOTSTRAP_ALLOWLIST=1
            ;;
        --staged)
            USE_STAGED=1
            ;;
        --worktree)
            USE_STAGED=0
            ;;
    esac
    shift
done

if [ "$USE_STAGED" = "1" ]; then
    DIFF_MODE="staged"
fi

if ! [[ "$MAX_CHANGED_FILES" =~ ^[0-9]+$ ]]; then
    MAX_CHANGED_FILES=40
fi
if [ "$MAX_CHANGED_FILES" -lt 1 ]; then
    MAX_CHANGED_FILES=1
fi
if ! [[ "$REQUIRE_ALLOWLIST" =~ ^(0|1)$ ]]; then
    REQUIRE_ALLOWLIST=1
fi
if ! [[ "$DIFF_MODE" =~ ^(worktree|staged)$ ]]; then
    DIFF_MODE="worktree"
fi

if [ "$DIFF_MODE" = "staged" ]; then
    git_output="$(git diff --cached --name-only 2>/dev/null || true)"
else
    git_output="$(git status --porcelain 2>/dev/null || true)"
fi
branch_name="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"

{
    echo "Release Worktree Check"
    echo "branch=${branch_name}"
    echo "max_changed_files=${MAX_CHANGED_FILES}"
    echo "allowlist_file=${ALLOWLIST_FILE}"
    echo "require_allowlist=${REQUIRE_ALLOWLIST}"
    echo "diff_mode=${DIFF_MODE}"
    echo "timestamp=$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo
} >"$REPORT_PATH"

if [ -z "$git_output" ]; then
    echo "status=clean" | tee -a "$REPORT_PATH" >/dev/null
    if [ "$DIFF_MODE" = "staged" ]; then
        echo "✅ staged diff clean: 릴리즈 체크 통과"
    else
        echo "✅ 워크트리 clean: 릴리즈 체크 통과"
    fi
    echo "📝 report: ${REPORT_PATH}"
    exit 0
fi

declare -a changed_paths=()
declare -a out_of_scope=()
allowlist_enabled=0
allowlist_entries=""

if [ -f "$ALLOWLIST_FILE" ]; then
    allowlist_enabled=1
    while IFS= read -r raw; do
        line="$(printf '%s' "$raw" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
        [ -z "$line" ] && continue
        [[ "$line" == \#* ]] && continue
        allowlist_entries="${allowlist_entries}${line}"$'\n'
    done <"$ALLOWLIST_FILE"
fi

while IFS= read -r line; do
    [ -z "$line" ] && continue
    if [ "$DIFF_MODE" = "staged" ]; then
        path="$line"
    else
        path="${line:3}"
        if [[ "$path" == *" -> "* ]]; then
            path="${path##* -> }"
        fi
    fi
    changed_paths+=("$path")
    if [ "$allowlist_enabled" -eq 1 ] && ! printf '%s' "$allowlist_entries" | grep -Fxq -- "$path"; then
        out_of_scope+=("$path")
    fi
done <<<"$git_output"

changed_count="${#changed_paths[@]}"
{
    echo "status=dirty"
    echo "changed_count=${changed_count}"
    echo
    echo "[changed_files]"
    printf '%s\n' "${changed_paths[@]}"
    echo
} >>"$REPORT_PATH"

if [ "$BOOTSTRAP_ALLOWLIST" = "1" ]; then
    {
        echo "# generated by scripts/check_release_worktree.sh --bootstrap-allowlist"
        echo "# $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        printf '%s\n' "${changed_paths[@]}"
    } >"$ALLOWLIST_FILE"
    echo "✅ allowlist 생성 완료: ${ALLOWLIST_FILE} (${changed_count}개)"
    echo "📝 report: ${REPORT_PATH}"
    exit 0
fi

if [ "$allowlist_enabled" -ne 1 ] && [ "$REQUIRE_ALLOWLIST" = "1" ]; then
    {
        echo "[violation]"
        echo "type=allowlist_missing"
        echo "message=dirty worktree requires allowlist file"
        echo
    } >>"$REPORT_PATH"
    echo "❌ 릴리즈 체크 실패: dirty 워크트리에서는 allowlist 파일(${ALLOWLIST_FILE})이 필요합니다."
    echo "📝 report: ${REPORT_PATH}"
    exit 1
fi

if [ "$allowlist_enabled" -eq 1 ]; then
    allowlist_entry_count="$(printf '%s' "$allowlist_entries" | awk 'NF > 0' | wc -l | tr -d ' ')"
    {
        echo "[allowlist]"
        echo "enabled=1"
        echo "entries=${allowlist_entry_count:-0}"
        echo
    } >>"$REPORT_PATH"
fi

if [ "$changed_count" -gt "$MAX_CHANGED_FILES" ]; then
    {
        echo "[violation]"
        echo "type=max_changed_files"
        echo "message=changed_count(${changed_count}) > max_changed_files(${MAX_CHANGED_FILES})"
        echo
    } >>"$REPORT_PATH"
    echo "❌ 릴리즈 체크 실패: 변경 파일 수가 너무 많습니다 (${changed_count} > ${MAX_CHANGED_FILES})"
    echo "📝 report: ${REPORT_PATH}"
    exit 1
fi

if [ "${#out_of_scope[@]}" -gt 0 ]; then
    {
        echo "[violation]"
        echo "type=allowlist"
        echo "message=allowlist 밖 파일이 포함되었습니다"
        printf '%s\n' "${out_of_scope[@]}"
        echo
    } >>"$REPORT_PATH"
    echo "❌ 릴리즈 체크 실패: allowlist 밖 파일이 있습니다 (${#out_of_scope[@]}개)"
    echo "📝 report: ${REPORT_PATH}"
    exit 1
fi

echo "✅ 릴리즈 워크트리 체크 통과 (changed=${changed_count})"
echo "📝 report: ${REPORT_PATH}"
